### ISSUE TITLE
Returning empty chunk

### ISSUE THREAD

**Issue by sepehrabdous** [inet-framework/inet#479] opened 2019-11-07 15:24 UTC
Hello
I have a simple simulation to simulation an incast traffic pattern. I have installed inet4 using omnet++ help tab and I only have a .NED and .INI  but when I try running it, after a short time of running and exchanging packets it pops up the following error:
**Returning an empty chunk is not allowed according to the flags: 0 -- in module (inet::tcp::Tcp) Tcp.server[1].tcp (id=92), at t=1.382841872s, event #38455** 

Attached you can find the zip file including codes of the .ned and .ini file.

[code.zip](https://github.com/inet-framework/inet/files/3820317/code.zip)

**Comment by levy** [comment] 2019-11-08 08:41
I downloaded your example and I can't reproduce this problem with the INET master branch, it runs just fine. I guess this was a bug in the older versions.

**Comment by sepehrabdous** [comment] 2019-11-08 13:43
Hello
Should I delete the inet associated with omnetpp and install it manually
from github??

**Comment by levy** [comment] 2019-11-08 14:25
It's enough if you temporarily remove the INET project from the workspace (don't delete, just remove) and import the one cloned from github.

**Comment by sepehrabdous** [comment] 2019-11-08 16:09
Thank you very much for your help.

**Comment by sepehrabdous** [comment] 2019-11-08 16:50
Quick question,
In the recent version of inet is there any changes to the framecapacity of
the switch queue.
Because I have the following lines in my .ini file and in the previous
version there were no warning but in the current version I get the unused
entry warning regarding the second line and I think when there is no
limited queue for the switch we would not get the *empty chunk* error even
in the previous version of inet:

**.switch.eth[*].queue.typename = "DropTailQueue"
**.switch.eth[*].queue.frameCapacity = 19

Best,
Sepehr

**Comment by levy** [comment] 2019-11-11 09:10
The capacity related queue parameters are called packetCapacity and dataCapacity. Also, the MAC parameters related to queue limits have been removed. So yes, the queueing model has been refactored quite a lot. See the WHATSNEW file for more details.

**Comment by levy** [comment] 2019-11-11 09:35
I've updated the parameters in your example and I'm still unable to reproduce this bug but I found another one in TCP, so we are going to investigate that. If you find this bug popping up again, then please let me know how to reproduce.

**Comment by levy** [comment] 2019-11-11 13:57
Ok, finally I was able to reproduce this. The trick was to use release mode instead of debug mode. The actual bug was in the TCP implementation related to timestamps. We fixed the TCP bug in the master branch, so it should work now. Could you please verify?

**Comment by sepehrabdous** [comment] 2019-11-11 16:15
I replaced inet and keep getting undefined symbol:
_ZNK4inet14InterfaceEntry10getNetmaskEv error.

**Comment by levy** [comment] 2019-11-11 16:25
Oh sorry, you can revert the last patch until it gets fixed.

**Comment by levy** [comment] 2019-11-13 13:50
Could you please check now?

**Comment by sepehrabdous** [comment] 2019-11-13 15:24
The undefined symbol error is removed. Thank you
But still there are some problems about the dataqueue.packetCapacity
In the file ./ipv6/nclients/omnetpp.ini, I'll opened it and there is a unused entry warning besides the line **.eth[*].mac.queue.dataQueue.packetCapacity = 10  # in routers

I have a switch with eth gates, how can I put capacity on eth queues?

**Comment by levy** [comment] 2019-11-14 13:32
Sometimes the INI file analyzer in the IDE is unable to determine the queue module type and thus it gives false warnings for parameter assignments. This is a known limitation. Please check the module in the simulation runtime if the parameter value is applied or not.

**Comment by levy** [comment] 2019-11-15 12:54
I close this because it's fixed now.

**Closed by levy** 2019-11-15 12:54 UTC
Labels: Bug

**Comment by sepehrabdous** [comment] 2019-11-15 15:37
Yes
I checked and it’s fixed.
Thank you
