### ISSUE TITLE
Classifier doesn't work

### ISSUE THREAD

**Issue by RKeiler** [inet-framework/inet#456] opened 2019-09-04 11:14 UTC
I've tried to create a queue with multifieldclassifier. Why does the classifier work only with the point to point protocol? It doesn't work with the ethernet connnection. If you use the ethernet connection then the messages goes to the default gate. 

Offtopic: How can you create multicast networks with ipv6? The framework provides only an example for ipv4. I guess the ipv6networkconfigurator is missing for this function.

**Comment by levy** [comment] 2019-11-05 10:32
It's unclear how to reproduce this issue. Which version are you using, what is the exact configuration, etc.

**Comment by levy** [comment] 2020-11-27 10:02
Closing because can't reproduce.

**Closed by levy** 2020-11-27 10:02 UTC
Labels: Can't reproduce
