### ISSUE TITLE
"Invalid gate Id -1" in networkLayer.neighbourDiscovery when adding a Ieee80211MgmtAP to NodeBase6

### ISSUE THREAD

**Issue by rhornig** [inet-framework/inet#84] opened 2015-03-13 16:52 UTC
The exact version is INET 2.1.0

I'm trying to simulate a NEtwork MObility environment so I need WirelessHost6 to act as a AP and AP client at the same time. To do so, I modify the NodeBase6 to add a new gate (radioAPIn) and APwlan with its connections but when I start the simulation on stage 3 I get the following error:

<!> Error in module (IPv6NeighbourDiscovery) nemo_handover_net.Mobile_Router.networkLayer.neighbourDiscovery (id=128) during network initialization: (cCompoundModule)nemo_handover_net.Mobile_Router: Invalid gate Id -1.

Where Mobile_Router is an instance of WirelessHost6.

If you need more information, please ask. Thanks in advance,
maddie

Additional Information  In order not to modify the original ned files I've created a NemoWirelessHost6 (attached) so you can use it in the example of xMIPv6 MIPv6Network.ned and reproduce it.

from: http://dev.omnetpp.org/bugs/view.php?id=650

**Comment by levy** [comment] 2019-11-06 09:48
I could not reproduce this bug and the initialization order of modules have been considerably refactored since, so I'll close this now as being obsolete.

**Closed by levy** 2019-11-06 09:48 UTC
Labels: Bug, Obsolete
