### ISSUE TITLE
Problem with the GCL feature

### ISSUE THREAD

**Issue by ar8384** [inet-framework/inet#897] opened 2023-07-03 13:25 UTC
Hello everyone,

I wanted to try the new GCL feature that came with INET 4.5. 
I ran the following simulation by adjusting the time-aware shaping showcase:
```c++
[General]
network = inet.networks.tsn.TsnLinearNetwork
sim-time-limit = 1s
description = "Traffic shaping using time-aware shapers"
outputvectormanager-class="omnetpp::envir::SqliteOutputVectorManager"
output-vector-file = results/resvec.sqlite

#**.displayGateSchedules = true
#**.gateFilter = "**.eth[1].**"
#**.gateScheduleVisualizer.height = 16
#**.gateScheduleVisualizer.placementHint = "top"

###########################################
#           Client configuration          #
###########################################
# client applications
*.client.numApps = 2
*.client.app[*].typename = "UdpSourceApp"
*.client.app[0].display-name = "best effort"
*.client.app[1].display-name = "video"
*.client.app[*].io.destAddress = "server"
*.client.app[0].io.destPort = 1000
*.client.app[1].io.destPort = 1001
*.client.app[0].source.packetLength = 1500B - 54B # 54B = 8B (UDP) + 20B (IP) + 14B (ETH MAC) + 4B (ETH FCS) + 8B (ETH PHY)
*.client.app[1].source.packetLength = 1500B - 54B # 54B = 8B (UDP) + 20B (IP) + 14B (ETH MAC) + 4B (ETH FCS) + 8B (ETH PHY)
*.client.app[0].source.productionInterval = uniform(0us, 400us)
*.client.app[1].source.productionInterval = exponential(400us)

# enable outgoing streams
*.client.hasOutgoingStreams = true

# client stream identification
*.client.bridging.streamIdentifier.identifier.mapping = [{stream: "best effort", packetFilter: expr(udp.destPort == 1000)}, {stream: "video", packetFilter: expr(udp.destPort == 1001)}]

# client stream encoding
*.client.bridging.streamCoder.encoder.mapping = [{stream: "best effort", pcp: 0}, {stream: "video", pcp: 4}]

###########################################
#           Server configuration          #
###########################################
# server applications
*.server.numApps = 2
*.server.app[*].typename = "UdpSinkApp"
*.server.app[0].io.localPort = 1000
*.server.app[1].io.localPort = 1001

##########################################
#          Switch configuration          #
##########################################
# enable egress traffic shaping
*.switch.hasEgressTrafficShaping = true

# disable forwarding IEEE 802.1Q C-Tag
*.switch.bridging.directionReverser.reverser.excludeEncapsulationProtocols = ["ieee8021qctag"]

# time-aware traffic shaping
*.switch.eth[*].macLayer.queue.numTrafficClasses = 2
*.switch.eth[*].macLayer.queue.*[0].display-name = "best effort"
*.switch.eth[*].macLayer.queue.*[1].display-name = "video"
*.switch.eth[*].macLayer.queue.gateControlList.hasGcl = true
*.switch.eth[*].macLayer.queue.gateControlList.numGates = 2
*.switch.eth[*].macLayer.queue.gateControlList.offset = 0ms
*.switch.eth[*].macLayer.queue.gateControlList.durations = [4ms, 2ms, 2ms, 2ms]
*.switch.eth[*].macLayer.queue.gateControlList.gateStates = ["10", "00", "01", "00"]
# The following configuration is the same as the one above.
#*.switch.eth[*].macLayer.queue.transmissionGate[0].offset = 0ms
#*.switch.eth[*].macLayer.queue.transmissionGate[0].durations = [4ms, 6ms] # period is 10
#*.switch.eth[*].macLayer.queue.transmissionGate[1].offset = 6ms
#*.switch.eth[*].macLayer.queue.transmissionGate[1].durations = [2ms, 8ms]
```

At the end, it seemed to me that using switch.eth[\*].macLayer.queue.gateControlList is not equivalent to using switch.eth[\*].macLayer.queue.transmissionGate as I got very different results... It seems that switch.eth[\*].macLayer.queue.gateControlList is more equivalent to no TSN scheduling...

Did I miss something in the configuration?

Thank you in advance ;)

**Comment by levy** [comment] 2023-10-09 08:23
The configuration line `*.switch.eth[*].macLayer.queue.gateControlList.hasGcl = true` is wrong. The `hasGcl` parameter is in the queue, so it should read `*.switch.eth[*].macLayer.queue.hasGcl = true` instead.

**Comment by ar8384** [comment] 2023-10-10 14:16
Thank you for your answer ;)

I'm not sure that this is the problem, as when I change `*.switch.eth[*].macLayer.queue.hasGcl = true`, the simulation finishes with an error: `Simulation terminated with exit code: 8b`
Whereas the simulation is running prefectly fine with `*.switch.eth[*].macLayer.queue.gateControlList.hasGcl = true`.

Thank you for your help

**Comment by levy** [comment] 2023-10-11 15:17
That may be caused by an entirely different issue. It's impossible to decide what happens from an exit code.

**Comment by levy** [comment] 2023-10-12 13:04
This has been fixed in the master branch. Could you please verify?

**Comment by ar8384** [comment] 2023-10-12 14:58
Hello,

I verified and the simulations are running without errors. 

I however ran into another problem: 
with this configuration:
```
*.switch.eth[*].macLayer.queue.hasGcl = true
*.switch.eth[*].macLayer.queue.gateControlList.numGates = 2
*.switch.eth[*].macLayer.queue.gateControlList.offset = 0ms
*.switch.eth[*].macLayer.queue.gateControlList.durations = [4ms, 2ms, 2ms, 2ms]
*.switch.eth[*].macLayer.queue.gateControlList.gateStates = ["10", "00", "01", "00"]
```
I obtain the following gate state:

![Gate states 1](https://github.com/inet-framework/inet/assets/68435241/4844c5f7-d61d-483e-b43a-ffd3d46b4ed8)

whereas it should look more to something like this, obtained with (which is I think the equivalent):
```
*.switch.eth[*].macLayer.queue.transmissionGate[0].offset = 0ms
*.switch.eth[*].macLayer.queue.transmissionGate[0].durations = [4ms, 6ms] # period is 10
*.switch.eth[*].macLayer.queue.transmissionGate[1].offset = 4ms # real offset = duration - offset
*.switch.eth[*].macLayer.queue.transmissionGate[1].durations = [2ms, 8ms]
```

![Gate states 2](https://github.com/inet-framework/inet/assets/68435241/07c0a57c-fb2b-4fc0-a7a3-ba4cb45d6826)

If I understood correctly, GateControlList is a translator toward PeriodicGate. If then, I should retrieve the same results from the sqlite result file.

Thank you very much and sorry to bother

**Comment by levy** [comment] 2023-10-12 15:59
No problem, it's valuable to get bug reports. This component was contributed by another INET user. I'll check what's going on.

**Comment by levy** [comment] 2023-10-13 09:39
I have pushed a fix on the master branch. Could you please verify if this solves the problem?

**Closed** 2023-10-13 09:38 UTC
Labels: Bug

**Comment by ar8384** [comment] 2023-10-15 09:37
It works.

I may have, however, found another issue (last one I hope).
When I change
```
*.switch.eth[*].macLayer.queue.numTrafficClasses = 2
*.switch.eth[*].macLayer.queue.hasGcl = true
*.switch.eth[*].macLayer.queue.gateControlList.numGates = 2
*.switch.eth[*].macLayer.queue.gateControlList.offset = 0ms
*.switch.eth[*].macLayer.queue.gateControlList.durations = [4ms, 2ms, 2ms, 2ms]
*.switch.eth[*].macLayer.queue.gateControlList.gateStates = ["10", "00", "01", "00"]
```
to
```
*.switch.eth[*].macLayer.queue.numTrafficClasses = 8
*.switch.eth[*].macLayer.queue.hasGcl = true
*.switch.eth[*].macLayer.queue.gateControlList.numGates = 8
*.switch.eth[*].macLayer.queue.gateControlList.offset = 0ms
*.switch.eth[*].macLayer.queue.gateControlList.durations = [4ms, 3ms, 2ms, 1ms]
*.switch.eth[*].macLayer.queue.gateControlList.gateStates = ["10000000", "01111111", "00000010", "00000001"]
```
I get the following error:
`(omnetpp::cValueArray): get(): index 2 is out of bounds -- in module (inet::queueing::GateControlList) TsnLinearNetwork.switch.eth[0].macLayer.queue.gateControlList (id=242), during network initialization`

In fact, the GCL seems to work when `numGates` = 1 or 2, and not when `numGates` = 3, 4, 5, 6, 7, 8 (and that the `gateStates` is set accordingly).

Is there another parameter that I missed?

**Comment by levy** [comment] 2023-10-15 13:05
I'm just guessing because I'm not in front of my computer right now. I
believe that the number of PeriodicGate submodules is still 2, you should
change that also to 8. IIRC it's the numTrafficCategories parametet.

I hope this helps,
levy

**Comment by ar8384** [comment] 2023-10-16 09:50
Hmm... there doesn't seem to be such a parameter... except `numTrafficClasses`, which I set to 8.

The parameters of PeriodicGates;
```
parameters:
        string clockModule = default(""); // relative path of a module that implements IClock; optional
        bool initiallyOpen @mutable = default(true); // specifies if the gate is initially open or closed
        double offset @mutable @unit(s) = default(0s); // specifies where the period starts in the list of gate state change durations; where it is in the period at the start
        object durations @mutable @unit(s) = default([]); // list of time durations within the period that determine if the gate is open or closed; period is the sum of the durations
        bool scheduleForAbsoluteTime = default(true); // when a clock is used relative means that setting the clock will not affect the simulation time of the event
        int openSchedulingPriority = default(0); // FES scheduling priority for the next gate open event
        int closeSchedulingPriority = default(0); // FES scheduling priority for the next gate close event
        bool enableImplicitGuardBand = default(true); // implicit guard band means that a packet is not allowed to be forwarded if it cannot finish transmission before the end of window.
        @class(PeriodicGate);
        @signal[guardBandStateChanged](type=bool);
        @statistic[guardBandState](title="guard band state"; type=enum; enum=ON, OFF; source=guardBandStateChanged; record=vector; interpolationmode=sample-hold);
```
The parameters of GateControlList:
```
parameters:
        int numGates = default(8);
        object durations @mutable @unit(s) = default([]); // list of entry durations, e.g. [4ms, 2ms, 2ms, 2ms]
        object gateStates @mutable = default([]); // list of gateStates, e.g. ["10000000", "01111111", "10000000", "01111111"]
        @class(GateControlList);
        @display("i=block/table");
```

As far as I remember, in PeriodicGates, there is no need to define the number of gates, as it is done like:
```
*.switch.eth[*].macLayer.queue.transmissionGate[0].offset = 0ms
*.switch.eth[*].macLayer.queue.transmissionGate[0].durations = [4ms, 6ms] # period is 10
*.switch.eth[*].macLayer.queue.transmissionGate[1].offset = 6ms
*.switch.eth[*].macLayer.queue.transmissionGate[1].durations = [2ms, 8ms]
```

**Comment by levy** [comment] 2023-10-18 08:27
This bug has been fixed in the master branch. I've noticed something though. The order of 1s and 0s in the GCL strings is applied to PeriodicGate submodules in reverse order. I don't know why it's implemented like that. For example, ["10" ,"10"] results in transmissionGate[0] to be closed and transmissionGate[1] to be open. For me, it would be more intuitive if the first digit would correspond to the first transmissionGate submodule, and the last digit would correspond to the last transmissionGate submodule. Do you think we should use the same order instead?

**Comment by Musteblume** [comment] 2023-10-18 08:34
This would be also more intuitive for me, but this screenshot from 802.1Q-2018 shows it in the currently implemented order:
![image](https://github.com/inet-framework/inet/assets/22887071/b8e92450-250d-447f-8db2-0d8fff85a221)

**Comment by ar8384** [comment] 2023-10-18 08:44
> This bug has been fixed in the master branch. I've noticed something though. The order of 1s and 0s in the GCL strings is applied to PeriodicGate submodules in reverse order. I don't know why it's implemented like that. For example, ["10" ,"10"] results in transmissionGate[0] to be closed and transmissionGate[1] to be open. For me, it would be more intuitive if the first digit would correspond to the first transmissionGate submodule, and the last digit would correspond to the last transmissionGate submodule. Do you think we should use the same order instead?

To be honest, this is the reason why i did this test with 8 queues:  I wanted to understand how the mapping was done.
As @Musteblume said, I guess the order is  76543201 (like in NeSTiNg) or 76543210. But I agree with you @levy , it would be more intuitive if the first digit would correspond to the first transmissionGate submodule.

**Comment by levy** [comment] 2023-10-18 09:36
While I understand @Musteblume's reasoning related to the standard I still have concerns. The traffic class to transmission gate index mapping is determined by the classifier submodule of the time-aware shaper compound queue (e.g. PcpTrafficClassClassifier), because that's the one that classifies and pushes packets into the subqueues. The gateControlList submodule has no way of knowing what this mapping is, and the classifier can be replaced by the user. So it means that the gateControlList submodule cannot reliably map gate states (1s and 0s) to traffic categories. It can only map gate states to transmission gate indices.

Maybe we should have a separate mapping parameter that specifies the gate indices? For example, mapping = "76543210" would mean the current behavior, that is mapping gate states to gate indices in reverse order. Unfortunately, this parameter would be required because there's no good default for a variable number of gates.

I'm not sure what to do, we can also leave it as it is right now. What's your opinion?

**Comment by Musteblume** [comment] 2023-10-18 13:26
I would lean towards index order (01234567) because this is what i would expect when configuring.

**Comment by ar8384** [comment] 2023-10-19 09:26
I agree that having a separate mapping parameter that specifies the gate indices is a good idea. This way, everyone is responsible for his own mapping and it will be clear which gate correpond to which indice.

**Comment by levy** [comment] 2023-10-19 13:24
I've pushed the mapping parameter change into master.
