### ISSUE TITLE
TCP SACK example assertion failure

### ISSUE THREAD

**Issue by torokati44** [inet-framework/inet#278] opened 2017-12-11 17:34 UTC
To reproduce:
Run `examples/inet/ber`, in the `ber-sack-experiment` configuration, choose run `#34 ($sack=true, $ber=1e-6, $repetition=4)`.
Fast forward to Event #1160250 in Express mode, then continue in any mode you wish.
In debug mode, the result is the following error message:

`<!> ASSERT: Condition 'seqLE(begin, fromSeqNum) && seqLess(fromSeqNum, end)' does not hold in function 'checkSackBlock' at inet/transportlayer/tcp/TCPSACKRexmitQueue.cc:375 -- in module (inet::tcp::TCP) ber.client.tcp (id=15), at t=96.45483795s, event #1160254
`

In release mode, the simulation just hangs there silently, hogging the CPU.

Present in master as of 2017-12-11, in commit bec0aba841c5570facee0e6e6df0fc013a17ce25 .

**Comment by ZoltanBojthe** [comment] 2019-11-06 10:31
can't reproduce,
is fixed in #415?

**Closed by ZoltanBojthe** 2019-11-06 10:31 UTC
Labels: Bug
