### ISSUE TITLE
Unexpected Guardband respectively a wrong credit evolution

### ISSUE THREAD

**Issue by PhilippComet** [inet-framework/inet#886] opened 2023-04-26 14:29 UTC
Hi everyone,

I observed in the attached testcase, a wrong guardBandStateChangedSignal respectively a wrong credit behavior. With the debugger mode I figured out that the first `updateIsInGuardBand()`- call at 0.000364s is invoked by an incoming changeTimer in creditBasedGate.cc when the credit value reaches zero. But immediately the guardband is turned off again by the periodicGate by an incoming changeTimer message that invokes the `processChangeTimer()` which in turn to closes the gate. 

It's is a bit weird, that this only happens one time at the beginning of the simulation, but then never again (tested with 5s simulation duration)

![grafik](https://user-images.githubusercontent.com/121798011/234602415-3c05f0cf-453f-45f6-80f5-db72edea2250.png)

It would be great if you could try to reproduce the error, so we could find a solution :)

Best regards,
Philipp

**ATTACHMENT:**
[testcase_gb_error.zip](https://github.com/inet-framework/inet/files/11333981/testcase_gb_error.zip)

**Comment by levy** [comment] 2023-04-26 14:41
Thanks for reporting the issue. Can you be a little bit more detailed about what is expected and what happens instead?

**Comment by PhilippComet** [comment] 2023-04-26 14:58
Thanks for your fast response. The correct behaviour should be that the credit reaches zero, the guardband-check should be invoked. When the frame is short enough to be served in the time window before the transmission gate closes, it should be dequeued, if not, the guardband signal should be emitted and keep active until the next transmission gate closing event. (see subsequent guardband signal path from 500us ongoing- this looks correct). The credit curve should not increase to values bigger than zero in this example.

In this case, the guardband is set as active but only for an infinitesimally small time duration. For me it looks like there are two simoultaneous incoming changeTimer events.

**Comment by levy** [comment] 2023-05-02 08:23
Thanks for the update! I was able to reproduce the problem.

The https://github.com/inet-framework/inet/tree/topic/creditbasedgate branch contains my first try to fix this issue. The problem was caused by opening/closing the gate from setCurrentCredit method. The gate state change caused other modules to react, the call chain reached back to the CreditBasedGate while it was in the middle of the original operation.

I'm still testing this change. Could you please take a look?

**Comment by PhilippComet** [comment] 2023-05-02 17:16
Thanks for your help and providing a solution approach!
The original attached testcase looks correct now also for me. I further also tested a more complex scenario that reveals another malfunction as you can see in the following two images:
The location of the signals you can see in the graph is Switch 1 Port 4:

![grafik](https://user-images.githubusercontent.com/121798011/235734798-2701e4ab-b4bf-48c8-b6ad-edd8cbd3c801.png)

![grafik](https://user-images.githubusercontent.com/121798011/235734896-4d9e88d3-cba2-49ab-b6d5-afc229066d8f.png)

**I have attached the relevant test case from the images here:**
[testcases.zip](https://github.com/inet-framework/inet/files/11375849/testcases.zip)

Some additional side facts to the network: 
- 12 End Stations (ES) and 4 Switches (SW)
- ES1-ES6 are traffic sending sources - ES7-ES12 are traffic sinks
- 15 ST Flows and 30 AVB Flows in the network. Routes are predefined by custom MAC table per switch
    the GCL for each egress port of End Station and Switch are precalculated externally to ensure Scheduled Traffic (ST) to meet its deadline
- implicit guardband **only** active for AVB traffic
- 10ms hyperperiod for GCL
- exclusive gating between ST and AVB Traffic => only one transmission gate is open at a time

**Comment by levy** [comment] 2023-05-05 09:05
I updated the topic/creditbasedgate branch with a series of small changes that fix the above issue. Could you please check if everything seems right?

**Comment by PhilippComet** [comment] 2023-05-06 10:00
Hi Levente,
thank you very much for your support and the new adjustments!

I did some extended testing with multiple AVB traffic classes shaped by CBS and different network loads. 
**Everything looks correct now** also for frozen and nonfrozen credit accumulation during guardband. 

Best Regards

**Comment by levy** [comment] 2023-05-08 13:16
Thanks for your contribution!

**Closed by levy** 2023-05-08 13:16 UTC
Labels: Bug
