### ISSUE TITLE
Missing control info in UDP

### ISSUE THREAD

**Issue by DenisLug** [inet-framework/inet#362] opened 2018-07-19 15:54 UTC
Hello,

some control infos of UDP like the UDPDataIndication are missing since INET 3.99. The [whatsnew documentation](https://github.com/inet-framework/inet/blob/v3.99.0/WHATSNEW#L54) writes, that the infos have been replaced by packet tags. In the simulation manual as well as in the code I could not find any note about these tags. 

Where can I find the packet tags and how do I use them?

Best Regards

**Comment by levy** [comment] 2018-07-26 09:08
The relevant tags are L3AddressInd, L4PortInd, InterfaceInd, SocketInd, NetworkProtocolInd, TransportProtocolInd, etc. and similarly, L3AddressReq, L4PortReq, etc.

This is not a bug, so I close this issue.

**Closed by levy** 2018-07-26 09:08 UTC
