### ISSUE TITLE
Problem with passive 802.11 interfaces withing a network node in coexistence scenario.

### ISSUE THREAD

**Issue by ababila** [inet-framework/inet#495] opened 2019-12-10 17:24 UTC
I remarked a really strange INET behavior in a coexistence scenario which may be related to this  [issue](https://github.com/inet-framework/inet/issues/248). 

**Scenario**:
Figure below illustrates the considered scenario. 
![Test1Scenario](https://user-images.githubusercontent.com/36278932/70541143-c7261f80-1b66-11ea-9773-6067c589102a.png)
The topology is similar to this [coexistence showcase](https://github.com/inet-framework/inet/tree/master/showcases/wireless/coexistence), except: 
(1) I do not use the dimensional analog models (yet), instead, I tweaked the code of `ScalarAnalogModelBase` to simulate the coexistence of the technologies from [this](https://github.com/inet-framework/inet/commit/f9bb5f9db20f528cf23d171ea9b0af9f88d9d2e5) commit on master. [Here](https://gist.github.com/ababila/bdec5cbc166f8bf586babc760a9189e9) is a `git diff` output of the local change I made after this commit. And [here](https://gist.github.com/ababila/08358a14feab856c6050e3f98cebebef) are the additional `.ned` and `.ini `files to reproduce this issue. 
(2) I added a run configuration that extends the base coexistence scenario to add simply a passive 802.11 interfaces to the` wpanHosts`. The default channel configuration of these passive interfaces does not even overlap with the channel of the 802.11 and 802.15.4 interfaces in the base scenario.

**Results:**
Figure below shows the average application throughput on the `wpanHost2` (traffic destination) as a function of a duty cycle of the coexisting WLAN for both configurations: blue curve for the scenario where there is only one 802.15.4 interface within the WPAN nodes and, the yellow curve for the scenario where there is an additional passive 802.11 interface.

![ResultBugReport](https://user-images.githubusercontent.com/36278932/70543999-9d232c00-1b6b-11ea-8fc2-bdb84e2313da.png)

**Issues:**
(1) The two curves should be superposed perfectly.
(2) The high points of the yellow curve mean the generated UDP traffic on 802.15.4 link is received with 0 protocol overhead.  
(3) There is a mysterious random factor that influences the results of the yellow figure. 
For example, the two figures below are further results obtained using the same code, the same configuration files, but just executed at different moments.  
![BugReport2](https://user-images.githubusercontent.com/36278932/70550654-5f77d080-1b76-11ea-9c05-bb9248e4e265.png)
![BugReport3](https://user-images.githubusercontent.com/36278932/70550663-61da2a80-1b76-11ea-80d6-a982b5fb14f2.png)

I'm using omnetpp 5.4.1 on Ubuntu 18.04.3 LTS.

**Comment by levy** [comment] 2019-12-11 08:57
I think this issue is not related to the issue you mentioned. Nevertheless, I see what you are trying to achieve with your patch. In fact, I already had the very same thing in mind with very similar implementation. The reason I didn't add the code is that it's unclear what effects on the error rates computed by the error model this mixing of overlapping signals has. Just by looking at the code, I can't figure out what causes the unexpected results, so I must dig deeper because I have a feeling that a bug is lurking underneath.

**Comment by torokati44** [comment] 2019-12-11 09:42
I wouldn't want to hijack this issue too much with irrelevant questions, but I'd just like to get some insight as to how you produced these graphs. Is this Python+matplotlib or something else? Have you exported the data from the IDE into CSV format, or used the pure-Python scave loader module? Did you use the [Python tutorial](https://docs.omnetpp.org/tutorials/pandas/)? Have you heard of the new result analysis features of OMNeT++ 6.0 (there are preview releases available already)?

**Comment by ababila** [comment] 2019-12-11 10:35
I didn't want to talk about these things too, thinking it's a detail, indeed it could be interesting. 
I am not entirely familiar with the Omnetpp's CSV exported results framework (yet). 
I save the results in SQLite format, then I use  [this Rmd](https://gist.github.com/ababila/71e6613c7448f353405dc4d8a2fa0fa5) script to export data and [this one](https://gist.github.com/ababila/f4c782be1e29f724b6631a0a3fd348b1) for display.

**Comment by torokati44** [comment] 2019-12-11 11:24
It is very much just an irrelevant detail in the scope of this issue, yes. I just saw your charts and was curious. Thanks for sharing your scripts!

**Comment by levy** [comment] 2019-12-12 09:57
I don't have the faintest idea why but if I run the simulations with opp_runall -b 1 then the results perfectly match. It looks like one simulation run is affecting the other in the same Cmdenv. Could you please verify?

**Comment by ababila** [comment] 2019-12-12 10:10
> I don't have the faintest idea why but if I run the simulations with opp_runall -b 1 then the results perfectly match. It looks like one simulation run is affecting the other in the same Cmdenv. Could you please verify?

**Comment by ababila** [comment] 2019-12-12 10:13
sorry guys !!! I accidentally click the button "close and comment"

**Comment by levy** [comment] 2019-12-12 10:14
I think that the problem is in INET and I'm looking for it right now. This issue should not be closed until we get this fixed. Ah, ok... :)

**Comment by levy** [comment] 2019-12-12 14:46
It's fixed in master by a03ac290e65d3d4d21f8db6e72aad8fcb38475a5

**Comment by ababila** [comment] 2019-12-12 23:59
I confirm the results match perfectly! Thank you @levy !!!

**Comment by ababila** [comment] 2019-12-13 07:51
To answer this comment from @levy
> I see what you are trying to achieve with your patch. ...  it's unclear what effects on the error rates computed by the error model this mixing of overlapping signals has. ...

Actually it's a little parade of my own (a bit inspired by [the world of NS3](https://www.nsnam.org/docs/models/html/spectrum.html) for similar stuff) since the recent problems of the dimensional models coming from MiXiM ([this one for instance](https://github.com/inet-framework/inet/issues/436)).
I plan to go soon to the new framework of dimensional models. Actually, I was waiting for the INET 4.2 release. 
:)

**Comment by levy** [comment] 2019-12-13 08:31
Oh, I see. You might be interested in these visualizations of INET: 
https://www.youtube.com/watch?v=ZaL5Ae3Fowk
https://www.youtube.com/watch?v=tpmc6EdHw5A

These features are already available in the master branch.

**Closed by levy** 2019-12-13 08:31 UTC
Labels: Bug
