### ISSUE TITLE
Inet visualizer is not working

### ISSUE THREAD

**Issue by shrit** [inet-framework/inet#445] opened 2019-05-27 14:12 UTC
I am getting this error each time I have to run or to use the inet visualizer  
gdb is not finding any error, since it is a ned error. 
All visualizer modules are giving similar error.
Any suggestions? 

`
omnetpp::common::opp_runtimeerror: Parse error in match expression: syntax error, unexpected $end, expecting STRINGLITERAL or NOT or '(' -- in module (inet::visualizer::NetworkConnectionCanvasVisualizer) VisualizationA.visualizer.canvasVisualizer.networkConnectionVisualizer (id=8), during network initialization`

**Comment by levy** [comment] 2019-09-26 07:06
Which OMNeT and INET versions are you using?

**Comment by shrit** [comment] 2019-09-26 16:41
At that time, I was using the git version of both of them

**Comment by avarga** [comment] 2019-09-26 19:27
Reason is likely a recent change in omnetpp master, which makes the empty string invalid syntax in MatchExpression. The empty string likely comes from the default value of some filter parameter of the visualizer module. Changing it to "*" should help.

**Comment by levy** [comment] 2019-11-05 13:46
I can't reproduce this, I guess because the meaning of empty string has been reverted back to the original meaning in omnetpp. So I'll close this, please reopen if this issue surfaces again.

**Closed by levy** 2019-11-05 13:46 UTC
Labels: Bug, Can't reproduce
